[package]
name = "test_error"
version = "0.1.0"
authors = ["Andrey Kruglov <kruglov.it@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
thiserror = "1.0.25"